### ISSUE TITLE
Error in line 156

### ISSUE THREAD

**Issue by guaribr** [mamut86/GTT#1]
Dear mamut86,

First of all, I am relatively new to R. I found your GTT package and I wanted to use it to get the topics from Google Trends. But I was not able to get data from it, so I tried to run the code and I found that there is an error in line 156 

> id <- strsplit(entity[[2]][[1]], "kg:")[[1]][2] # ID

> Error in strsplit(entity[[2]][[1]], "kg:") : non-character argument

And maybe this is why the code doesn't run. Thanks!

**Comment by mamut86** [comment]
Hi @guaribr,

Thanks a lot for pointing this out. It appears that the API does not return all variables in the same order. This has now been fixed with the latest commit.
